actors:
  ずんだもん:
    image_url: /images/actors/zunmon001_square.png
    name: ずんだもん
    url: https://zund-arm-on.com/
    # url: https://takaaki-inada.github.io/
  ずんだどん:
    image_url: /images/actors/zundadon.jpg
    name: ずんだどん
    url: https://zund-arm-on.com/
  春日部つむぎ:
    image_url: /images/actors/春日部つむぎ立ち絵_公式_v1.1.1.png
    name: 春日部つむぎ
    url: https://zund-arm-on.com/
author: 株式会社ずんだもん技術室AI放送局
description: AIやテクノロジーのトレンドを届けるPodcast。平日毎朝6時配信。朝の通勤時間や支度中に情報キャッチアップとして聞いてほしいのだ。
description_long: AIやテクノロジーのトレンドを届けるPodcast。平日毎朝6時配信。朝の通勤時間や支度中に情報キャッチアップとして聞いてほしいのだ。
email: takaaki.inada@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
  - marp.config.mjs
  - package.json
  - package-lock.json
  - public
  - src
  - node_modules
  - tmp
  - next.config.js
  - next-env.d.ts
  - postcss.config.js
  - tailwind.config.js
  - tsconfig.json
  - watch.json
google_analytics:
hashtag: AIずんだもん
itunes_podcast_url:
keywords: AI, テクノロジー, ニュース
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 株式会社ずんだもん技術室AI放送局
url: https://zund-arm-on.com/
# url: https://takaaki-inada.github.io/
